restauring pipeliens

diff --git a/.github/workflows/build-gui-linux.yml b/.github/workflows/build-gui-linux.yml
--- a/.github/workflows/build-gui-linux.yml
+++ b/.github/workflows/build-gui-linux.yml
@@ -5,10 +5,10 @@ on:
     branches: [ main, develop, develop-weekly ]
   pull_request:
     branches: [ main, develop, develop-weekly ]
-  # workflow_run:
-  #   workflows: ["Build Linux"]
-  #   types:
-  #     - completed
+  workflow_run:
+    workflows: ["Build Linux"]
+    types:
+      - completed
   workflow_dispatch:
 
 jobs:
@@ -16,11 +16,11 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-    # - name: Check workflow run conclusion
-    #   if: ${{ github.event.workflow_run.conclusion != 'success' }}
-    #   run: |
-    #     echo "Core build workflow failed or was cancelled"
-    #     exit 1
+    - name: Check workflow run conclusion
+      if: ${{ github.event.workflow_run.conclusion != 'success' }}
+      run: |
+        echo "Core build workflow failed or was cancelled"
+        exit 1
     
     - name: Checkout repository
       uses: actions/checkout@v4
diff --git a/.github/workflows/build-gui-macos.yml b/.github/workflows/build-gui-macos.yml
--- a/.github/workflows/build-gui-macos.yml
+++ b/.github/workflows/build-gui-macos.yml
@@ -1,14 +1,10 @@
 name: Build GUI macOS
 
 on:
-  push:
-    branches: [ main, develop, develop-weekly ]
-  pull_request:
-    branches: [ main, develop, develop-weekly ]
-  # workflow_run:
-  #   workflows: ["Build Windows (Cross-Compile)"]
-  #   types:
-  #     - completed
+  workflow_run:
+    workflows: ["Build macOS"]
+    types:
+      - completed
   workflow_dispatch:
 
 jobs:
@@ -16,11 +12,11 @@ jobs:
     runs-on: macos-15
     
     steps:
-    # - name: Check workflow run conclusion
-    #   if: ${{ github.event.workflow_run.conclusion != 'success' }}
-    #   run: |
-    #     echo "Core build workflow failed or was cancelled"
-    #     exit 1
+    - name: Check workflow run conclusion
+      if: ${{ github.event.workflow_run.conclusion != 'success' }}
+      run: |
+        echo "Core build workflow failed or was cancelled"
+        exit 1
     
     - name: Checkout repository
       uses: actions/checkout@v4
@@ -178,11 +174,11 @@ jobs:
     runs-on: macos-15-intel
     
     steps:
-    # - name: Check workflow run conclusion
-    #   if: ${{ github.event.workflow_run.conclusion != 'success' }}
-    #   run: |
-    #     echo "Core build workflow failed or was cancelled"
-    #     exit 1
+    - name: Check workflow run conclusion
+      if: ${{ github.event.workflow_run.conclusion != 'success' }}
+      run: |
+        echo "Core build workflow failed or was cancelled"
+        exit 1
     
     - name: Checkout repository
       uses: actions/checkout@v4
diff --git a/.github/workflows/build-gui-windows.yml b/.github/workflows/build-gui-windows.yml
--- a/.github/workflows/build-gui-windows.yml
+++ b/.github/workflows/build-gui-windows.yml
@@ -1,14 +1,10 @@
 name: Build GUI Windows
 
 on:
-  push:
-    branches: [ main, develop, develop-weekly ]
-  pull_request:
-    branches: [ main, develop, develop-weekly ]
-  # workflow_run:
-  #   workflows: ["Build Windows (Cross-Compile)"]
-  #   types:
-  #     - completed
+  workflow_run:
+    workflows: ["Build Windows (Cross-Compile)"]
+    types:
+      - completed
   workflow_dispatch:
 
 jobs:
@@ -16,12 +12,11 @@ jobs:
     runs-on: windows-latest
     
     steps:
-    # - name: Check workflow run conclusion
-    #   if: ${{ github.event.workflow_run.conclusion != 'success' }}
-    #   run: |
-    #     echo "Core build workflow failed or was cancelled"
-    #     exit 1
-    
+    - name: Check workflow run conclusion
+      if: ${{ github.event.workflow_run.conclusion != 'success' }}
+      run: |
+        echo "Core build workflow failed or was cancelled"
+        exit 1
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
